name: 'Setup'
description: 'Setup environment with Java 17, Node 16.14.0'
runs:
  using: 'composite'
  steps:
    - name: 'Setup: Node.js'
      uses: actions/setup-node@v3
      with:
        node-version: 16.14.0
    - name: 'Setup: update NPM'
      shell: bash
      run: npm install -g npm
    - name: 'Setup: Java 17'
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17.x'
    - name: 'Setup: check tools'
      shell: bash
      run: |
        node -v
        npm -v
        java -version
