FROM ubuntu:22.10
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/jhlite /work/application

EXPOSE 7471
USER 1001

CMD ["./application"]
