export enum Service {
  INITIALIZATION = 'INITIALIZATION',
  MAVEN = 'MAVEN',
  JAVA_BASE = 'JAVA_BASE',
  SPRINGBOOT = 'SPRINGBOOT',
  SPRINGBOOT_MVC_WITH_TOMCAT = 'SPRINGBOOT_MVC_WITH_TOMCAT',
  ANGULAR = 'ANGULAR',
  REACT = 'REACT',
  VUE = 'VUE',
  FRONTEND_MAVEN_PLUGIN = 'FRONTEND_MAVEN_PLUGIN',
  UNKNOWN = 'UNKNOWN',
}
