FROM sonarqube:9.3.0-community
FROM jhipster/consul-config-loader:v0.4.1
FROM jhipster/jhipster-registry:v7.3.0
FROM jboss/keycloak:16.1.1
FROM mariadb:10.8.2
FROM mongo:5.0.6
FROM mysql:8.0.27
FROM postgres:14.2

