FROM sonarqube:9.2.4-community
FROM jhipster/consul-config-loader:v0.4.1
FROM jhipster/jhipster-registry:v7.3.0
FROM jboss/keycloak:16.1.0
FROM mariadb:10.8.2
FROM mongo:4.4.11
FROM mysql:8.0.27
FROM postgres:14.1

